### ISSUE TITLE
Prototyping

### ISSUE THREAD

**Issue by Dasniper4145** [Cataclysmanic/GO2022#1]
We will want to make sure that whatever we end up making is, at its core, fun. As such, we will want to make a PLAYABLE version of whatever it is, as fast as possible. Even if its just a box with the basic controls we want to implement.

**Comment by Dasniper4145** [comment]
Gonna create some basic topdown movement, with WASD and point and click to interact/shoot.
Important - ensure controls work with controller if possible.

**Comment by NuttyNutHead** [comment]
I'll prototype a rain effect and also a flashlight type vision blocker system.

**Comment by Dasniper4145** [comment]
Todo: Stealth system, enemies

**Comment by plexsoup** [comment]
Closing this because everything we do is prototyping.
