### ISSUE TITLE
Setup preliminary Game menus and Scene transitions

### ISSUE THREAD

**Issue by Cataclysmanic** [Cataclysmanic/GO2022#11]
Basics: Splash Screen, main menu, end-screen.
Maybe transitions.
Incorporate audio and animation if needed.

Switch to scenes entirely, or have Main.tscn instantiate and free levels as needed.

**Comment by plexsoup** [comment]
I modified the scene transitions, so they no longer rely on get_tree().change_scene().
Now, they use the change_scene() method on Main.gd.
To call it, use: Global.world_controller.change_scene(pathToScene), or Global.world_controller.change_scene_to(packedScene)

This will let us keep Main.tscn active in memory for things like loading and saving game files.

**Comment by plexsoup** [comment]
added a basic rain shader to the main menu
