### ISSUE TITLE
Tommy's house is wrong in intro animatic

### ISSUE THREAD

**Issue by plexsoup** [Cataclysmanic/GO2022#124]
For Tommy's house, where the murder happens, the intro cinematic doesn't match the in-game asset.

change the intro cinematic to match the actual residence, or vice versa.

**Comment by Volcanohman** [comment]
Also the Veronica used in intro has a different sprite than the paperdoll used for her fight

**Comment by plexsoup** [comment]
changed the Veronica Sprite in the intro.

**Comment by plexsoup** [comment]
and changed Tommys house
