### ISSUE TITLE
After viewing an ending animatic, starting a new game from the main menu doesn't work properly

### ISSUE THREAD

**Issue by plexsoup** [Cataclysmanic/GO2022#126]
consider adding a full blown restart to the ending buttons on the ending.

get_tree().change_scene(path)

**Comment by Volcanohman** [comment]
also consider making the endings more clear- people may think it's only a cutscene or expect more slides after the second so a text on the bottom (e.g. Ending 1) may help

**Comment by plexsoup** [comment]
reboot button now performs a hard restart.
I added the label at the bottom.
I put a final credits card into the animatics as well.
